# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Carta', folder: 'pages', file: 'carta'}
- {name: 'Juegos', folder: 'pages', file: 'juegos'}
- {name: 'Videojuegos', folder: 'pages', file: 'videojuegos'}
- {name: 'Servicios', folder: 'pages', file: 'servicios'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/devhouse.pe'}
- {icon: 'instagram', link: 'https://instagram.com/devhouse.pe'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text

post_date_prefix: 'Written on'
